---
# this is a simple pod manifest to create a simple nginx pod with logger sidecar container
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app=webapp
spec:
  containers:
   - name: nginx-container
     image: nginx
   - name: logger
     image: busybox
     volumeMounts:
       - name: logpath
         mountPath: /var/logger
     ports:
       - containerPort: 8080
...
     
